// src/data/players.ts
export const PLAYERS_DATA = {
    goalkeeper: [
        { name: "Alisson Becker", country: "Brazil" },
        { name: "Ederson", country: "Brazil" },
        { name: "Thibaut Courtois", country: "Belgium" },
        { name: "Manuel Neuer", country: "Germany" },
        { name: "Gianluigi Donnarumma", country: "Italy" },
        { name: "Marc-André ter Stegen", country: "Germany" },
        { name: "David de Gea", country: "Spain" },
        { name: "Keylor Navas", country: "Costa Rica" },
        { name: "Hugo Lloris", country: "France" },
        { name: "Emiliano Martínez", country: "Argentina" },
        { name: "Wojciech Szczęsny", country: "Poland" },
        { name: "Mike Maignan", country: "France" },
        { name: "Jan Oblak", country: "Slovenia" },
        { name: "Yassine Bounou", country: "Morocco" },
        { name: "Jordan Pickford", country: "England" },
        { name: "Unai Simón", country: "Spain" },
        { name: "Bernd Leno", country: "Germany" },
        { name: "Kepa Arrizabalaga", country: "Spain" },
        { name: "Aaron Ramsdale", country: "England" },
        { name: "Alex Meret", country: "Italy" },
        { name: "Illan Meslier", country: "France" },
        { name: "André Onana", country: "Cameroon" },
        { name: "José Sá", country: "Portugal" },
        { name: "Dominik Livaković", country: "Croatia" },
        { name: "Odysseas Vlachodimos", country: "Greece" }
    ],

    defender: [
        { name: "Virgil van Dijk", country: "Netherlands" },
        { name: "Rúben Dias", country: "Portugal" },
        { name: "Sergio Ramos", country: "Spain" },
        { name: "Trent Alexander-Arnold", country: "England" },
        { name: "João Cancelo", country: "Portugal" },
        { name: "Marquinhos", country: "Brazil" },
        { name: "Kalidou Koulibaly", country: "Senegal" },
        { name: "Raphaël Varane", country: "France" },
        { name: "Eder Militão", country: "Brazil" },
        { name: "Theo Hernández", country: "France" },
        { name: "Andrew Robertson", country: "Scotland" },
        { name: "Antonio Rüdiger", country: "Germany" },
        { name: "Ben Chilwell", country: "England" },
        { name: "Achraf Hakimi", country: "Morocco" },
        { name: "Alphonso Davies", country: "Canada" },
        { name: "Jules Koundé", country: "France" },
        { name: "Dayot Upamecano", country: "France" },
        { name: "Matthijs de Ligt", country: "Netherlands" },
        { name: "Presnel Kimpembe", country: "France" },
        { name: "Luke Shaw", country: "England" },
        { name: "Reece James", country: "England" },
        { name: "Pau Torres", country: "Spain" },
        { name: "César Azpilicueta", country: "Spain" },
        { name: "Álex Grimaldo", country: "Spain" },
        { name: "Robin Gosens", country: "Germany" },
        { name: "Nico Schlotterbeck", country: "Germany" }
    ],

    midfielder: [
        { name: "Kevin De Bruyne", country: "Belgium" },
        { name: "Luka Modrić", country: "Croatia" },
        { name: "Toni Kroos", country: "Germany" },
        { name: "Joshua Kimmich", country: "Germany" },
        { name: "N'Golo Kanté", country: "France" },
        { name: "Frenkie de Jong", country: "Netherlands" },
        { name: "Bruno Fernandes", country: "Portugal" },
        { name: "Jude Bellingham", country: "England" },
        { name: "Casemiro", country: "Brazil" },
        { name: "Ilkay Gündogan", country: "Germany" },
        { name: "Rodri", country: "Spain" },
        { name: "Marco Verratti", country: "Italy" },
        { name: "Pedri", country: "Spain" },
        { name: "Gavi", country: "Spain" },
        { name: "Eduardo Camavinga", country: "France" },
        { name: "Mason Mount", country: "England" },
        { name: "Thiago Alcântara", country: "Spain" },
        { name: "Declan Rice", country: "England" },
        { name: "Federico Valverde", country: "Uruguay" },
        { name: "Nicolo Barella", country: "Italy" },
        { name: "Adrien Rabiot", country: "France" },
        { name: "Leon Goretzka", country: "Germany" },
        { name: "Alexis Mac Allister", country: "Argentina" },
        { name: "Enzo Fernández", country: "Argentina" },
        { name: "Youri Tielemans", country: "Belgium" }
    ],

    attacker: [
        { name: "Lionel Messi", country: "Argentina" },
        { name: "Cristiano Ronaldo", country: "Portugal" },
        { name: "Kylian Mbappé", country: "France" },
        { name: "Erling Haaland", country: "Norway" },
        { name: "Harry Kane", country: "England" },
        { name: "Karim Benzema", country: "France" },
        { name: "Robert Lewandowski", country: "Poland" },
        { name: "Neymar Jr.", country: "Brazil" },
        { name: "Mohamed Salah", country: "Egypt" },
        { name: "Vinícius Júnior", country: "Brazil" },
        { name: "Lautaro Martínez", country: "Argentina" },
        { name: "Gabriel Jesus", country: "Brazil" },
        { name: "Antoine Griezmann", country: "France" },
        { name: "João Félix", country: "Portugal" },
        { name: "Phil Foden", country: "England" },
        { name: "Riyad Mahrez", country: "Algeria" },
        { name: "Ousmane Dembélé", country: "France" },
        { name: "Raheem Sterling", country: "England" },
        { name: "Richarlison", country: "Brazil" },
        { name: "Bukayo Saka", country: "England" },
        { name: "Federico Chiesa", country: "Italy" },
        { name: "Ángel Di María", country: "Argentina" },
        { name: "Darwin Núñez", country: "Uruguay" },
        { name: "Christian Pulisic", country: "USA" },
        { name: "Cody Gakpo", country: "Netherlands" },
        { name: "Ansu Fati", country: "Spain" }
    ]
};
